from setuptools import setup, find_packages

setup(
    name="aclimate_api",
    version="0.1",
    author="Minotriz02",
    author_email="sebastian.lopez@cgiar.org",
    description="API for the AClimate project",
    url="https://github.com/CIAT-DAPA/aclimatepyapi",
    download_url="https://github.com/CIAT-DAPA/aclimatepyapi",
    packages=find_packages('src'),
    package_dir={'': 'src'},
    install_requires=[
        'affine==2.4.0',
        'attrs==23.2.0',
        'certifi==2024.2.2',
        'charset-normalizer==3.3.2',
        'click==8.1.7',
        'click-plugins==1.1.1',
        'cligj==0.7.2',
        'colorama==0.4.6',
        'fiona==1.9.6',
        'geopandas==0.14.4',
        'idna==3.7',
        'importlib_metadata==7.1.0',
        'numpy==1.26.4',
        'packaging==24.0',
        'pandas==2.2.2',
        'pyparsing==3.1.2',
        'pyproj==3.6.1',
        'python-dateutil==2.9.0.post0',
        'pytz==2024.1',
        'rasterio==1.3.10',
        'requests==2.31.0',
        'shapely==2.0.4',
        'six==1.16.0',
        'snuggs==1.4.7',
        'tzdata==2024.1',
        'urllib3==2.2.1',
        'zipp==3.18.2',
    ],
    keywords=["aclimate", "api", "climate", "agriculture"],
)